const FRAME_RATE = 4;

const SQUARE_SIZE = 20;
const SQUARES_IN_WIDTH = 12;
const SQUARES_IN_HEIGHT = 20;

const BOARD_WIDTH = SQUARES_IN_WIDTH * SQUARE_SIZE;
const BOARD_HEIGHT = SQUARES_IN_HEIGHT * SQUARE_SIZE;

const CANVAS_WIDTH = BOARD_WIDTH * 4 / 3;
const CANVAS_HEIGHT = BOARD_HEIGHT;

const SCORE_PER_LANDING = 10;
const SCORE_PER_CLEAR_ROW = 100;